name = "arcmath_verifier"
version = "0.1.0"
defaultTargets = ["ArcmathVerifier"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "4fceb4697e54f6bbea184bf4ecfc0296a1110f3e"

[[lean_lib]]
name = "ArcmathVerifier"

[[lean_exe]]
name = "arcmath_verifier"
root = "Main"
